[workspace]
members = [
	"lego-powered-up",
	"pu-util",
	"lpu-macros",

	"examples/*",
]
default-members = ["pu-util", "lego-powered-up"]


[patch.crates-io]
lpu-macros = { path = "lpu-macros" }
lego-powered-up = { path = "lego-powered-up" }