[package]
name = "lego-powered-up"
version = "0.1.0"
authors = ["David Young <david@thedavidyoung.co.uk>"]
edition = "2018"
license = "MPL-2.0"
repository = "https://github.com/sciguy16/lego-powered-up"
description = "Control Lego PoweredUp hubs and devices"
readme = "../README.md"


# See more keys and their definitions at
# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
btleplug = "0.7"
crossbeam-channel = "0.5"
lazy_static = "1.4"
log = "0.4"
lpu-macros = "0.1"
num-derive = "0.3"
num-traits = "0.2"
rand = "0.8"
uuid = "0.8"

[dev-dependencies]
env_logger = "0.9"
