[package]
name = "lego-powered-up"
version = "0.1.0"
authors = ["David Young <david@thedavidyoung.co.uk>"]
edition = "2018"


# See more keys and their definitions at
# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
btleplug = "0.7"
lazy_static = "1.4"
log = "0.4"
lpu-macros = { path = "../lpu-macros" }
num-derive = "0.3"
num-traits = "0.2"
rand = "0.8"
tokio = { version ="1.6", features = ["full"] }
uuid = "0.8"

[dev-dependencies]
env_logger = "0.8"
